# Generated by Django 3.1.4 on 2020-12-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
