# Generated by Django 3.1.4 on 2020-12-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201228_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='main',
            name='pt',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='main',
            name='vm',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.TextField(default='#'),
        ),
    ]
