# Generated by Django 3.1.4 on 2020-12-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201229_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl2',
            field=models.TextField(default=''),
        ),
    ]
