# Generated by Django 3.1.4 on 2020-12-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='date',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='time',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
