# Generated by Django 3.1.4 on 2020-12-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='catname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
