# Generated by Django 4.0.3 on 2022-04-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Date',
            new_name='DateOfJoining',
        ),
    ]
