# Generated by Django 3.1.4 on 2020-12-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201218_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cat_name',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_text',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
