# Generated by Django 3.1.4 on 2020-12-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='catid',
            field=models.TextField(default='0'),
        ),
    ]
