version: "3.3"
services:
  jenkins-ansible:
    container_name: jenkins-ansible-server
    build:
      context: ./jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
    networks:
      - net
  remote-host:
    container_name: remote-host
    build:
      context: ./centos
    networks:
      - net
networks:
  net: